server:
  port: 52601
 
spring:
  application:
    name: config-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

info: Download successfully
